### ISSUE TITLE
Crash if LabView exits close to --kill-timeout

### ISSUE THREAD

**Issue by JonasEr** [JamesMc86/G-CLI#106]
## Description
There seems to be some race condition where G-Cli receives the `Process.Exited` event but still manages to find the PID once it checks if it's still running with `Process.GetProcessesByName`

## Test snippet to replicate
Run it with
`g-cli --verbose --kill --lv-ver 2017 --timeout 240000 "RunMe.vi" -- 10000 9300`

Where the first argument is some kind of fake time that the VI is "busy" and the second is the time that the VI should wait between sending the G-CLI Exit message and closing the LabView process.

_Note: There was some finetuning of the two delays before it could be replicated.
First I adjusted the "9300" time to find a spot where it is very close to being "killed" by G-Cli, but still manages to shut down before it happens._

![RunMe](https://user-images.githubusercontent.com/8407728/133422716-90e896e7-c16b-4996-900f-8b960b180b5c.png)

### Output when running from CMD:
```
g-cli --verbose --kill --lv-ver 2017 --timeout 240000 "RunMe.vi" -- 10000 9300
G CLI Started - Verbose Mode
Version 2.4.0.4 64-Bit
G CLI Arguments: --verbose --kill --lv-ver 2017 --timeout 240000 RunMe.vi
Arguments passed to LabVIEW: 10000 9300
Current Version: 2017 SP1, 32bit
Detected LabVIEW versions:
2017 SP1, 32bit(C:\Program Files (x86)\National Instruments\LabVIEW 2017\)
2019 SP1 f4, 32bit(C:\Program Files (x86)\National Instruments\LabVIEW 2019\)
2017 SP1, 64bit(C:\Program Files\National Instruments\LabVIEW 2017\)
Launching Program:
C:\Program Files (x86)\National Instruments\LabVIEW 2017\LabVIEW.exe "RunMe.vi" -unattended -- -p:64859
LabVIEW/App started, process ID is 6828
Waiting for connection on port 64859
Client Connected
Simulated VI run time 10000 ms
Delay after G-CLI exit 9300 ms
Time remaining 10 s
Time remaining 9 s
Time remaining 8 s
Time remaining 7 s
Time remaining 6 s
Time remaining 5 s
Time remaining 4 s
Time remaining 3 s
Time remaining 2 s
Time remaining 1 s
Received Exit Code 0
Forcing LabVIEW to terminate in 10000ms if it doesn't close.
Forcing LabVIEW to terminate...
LabVIEW process exited. Checking for process switch
LabVIEW still found with PID 6828

Unhandled Exception: System.InvalidOperationException: Cannot process request because the process (6828) has exited.
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   at System.Diagnostics.Process.set_EnableRaisingEvents(Boolean value)
   at G_CLI.LvLauncher.Process_Exited(Object sender, EventArgs e)
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Diagnostics.Process.get_HasExited()
   at G_CLI.LvLauncher.Kill()
   at G_CLI.Program.Main(String[] args)
   ```

**Comment by JamesMc86** [comment]
Thanks for the report! 

I think your explanation makes sense and I'll have to look what I can do. Unfortunately, as we don't have full control over the LabVIEW process I'm not sure what the solution is likely to be but definitely detecting that case and acting more gracefully would be good.

**Comment by JonasEr** [comment]
No worries!
I'm not too familiar with C Sharp, but I had a look and there was something in the Process class that mentioned caching its properties.
So perhaps this line https://github.com/JamesMc86/G-CLI/blob/9bbeb28d801d05c9f48bfe67b1461e87fd579db7/C%20Sharp%20Source/LabVIEW%20CLI/LvLauncher.cs#L207 is getting some old information?
Once again, not a C sharp programmer 😄

**Comment by samsharp99** [comment]
@JamesMc86 I have also started seeing the same issue recently - it seems to be quite intermittent but has started to cause quite a few of our builds to fail when running unit tests. For us though it isn't an issue with the --kill-timeout flag as we're not using it.

```
[UNIT TEST] Running Unit Tests (JKI VI Tester) in 'c:\jenkins\workspace\Vaya_PR-264\Source Code\Hermes.lvproj'.
[UNIT TEST] Report Path: c:\jenkins\workspace\Vaya_PR-264\Builds\Unit Test Reports\Unit Test Report.xml
[UNIT TEST] Unit Tests Passed.
[UNIT TEST] Duration: 604s

Unhandled Exception: System.InvalidOperationException: Cannot process request because the process (5012) has exited.
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   at System.Diagnostics.Process.set_EnableRaisingEvents(Boolean value)
   at G_CLI.LvLauncher.Process_Exited(Object sender, EventArgs e)
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Diagnostics.Process.get_HasExited()
   at G_CLI.LvLauncher.Kill()
   at G_CLI.Program.Main(String[] args)
```

**Comment by JamesMc86** [comment]
Thanks Sam. I'll move this up my priorities as it should be simple enough to supress.

**Comment by samsharp99** [comment]
> Thanks Sam. I'll move this up my priorities as it should be simple enough to supress.

Great, thanks James - if you want me to try/test an updated build to see if it fixes the issue then I'd be happy to - you know how to reach me. I do think there might be a workaround on the Jenkins side to suppress that particular exit code/message?

**Comment by JamesMc86** [comment]
I've taken a look at fixing this and it isn't quite as obvious as I had hoped. The error happens in an event callback triggered by the closing of the process.

Because I'm getting close to replacing the C# anyway (I'm hoping to have a pre-release version by the end of the month) I'm reluctant to spend time on this to be honest. If anything delays that process though I will come back to this.
